output_dir: ~/scratch/torchglycan_output/

dataset:
  class: GlycanClassification
  path: ~/scratch/glycan-datasets/
  target_fields: ["domain", "kingdom", "phylum", "class", "order", "family", "genus", "species"]
  unit_feature: default
  link_feature: default

task:
  class: GlycanPropertyPrediction
  model:
    class: GlycanResNet
    glycoword_dim: 216
    input_dim: 512
    hidden_dims: [512, 512, 512, 512, 512, 512, 512, 512]
    layer_norm: True
    dropout: 0.1
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  num_class: [4, 11, 39, 101, 210, 415, 922, 1737]
  # adjust: uw [-2]         # uncertainty weighting, [logvar]
  # adjust: ts [-2]         # temperature scaling, [logvar]
  # adjust: dwa [2]         # dynamic weight averaging, [T]
  # adjust: dtp [1]         # dynamic task prioritization, [gamma]
  # adjust: gn [1]          # gradnorm, [alpha]
  # adjust: norm            # loss normalization


metric: accuracy [average]

optimizer:
  class: Adam
  lr: 1.0e-4

mtl_lr: 2.5e-2

engine:
  gpus: {{ gpus }}
  batch_size: 64

train:
  num_epoch: 50
