output_dir: ~/scratch/torchglycan_output/

dataset:
  class: GlycanImmunogenicity
  path: ~/scratch/glycan-datasets/
  target_fields: ["immunogenicity"]
  unit_feature: default
  link_feature: default

task:
  class: GlycanImmunogenicity
  model:
    class: GlycanGCN
    num_unit: 143
    input_dim: 128
    hidden_dims: [128, 128, 128]
    concat_hidden: True
    readout: dual
  criterion: ce
  criterion: bce
  metric: ["auroc", "auprc"]

metric: auroc [immunogenicity]

optimizer:
  class: Adam
  lr: 5.0e-4
  weight_decay: 0.001

engine:
  gpus: {{ gpus }}
  batch_size: 256

train:
  num_epoch: 50
  
scheduler:
  class: CosineAnnealingLR
  T_max: 100
