output_dir: ~/scratch/torchglycan_output/

dataset:
  class: ProteinGlycanInteraction
  path: ~/scratch/glycan-datasets/
  unit_feature: default
  link_feature: default
  atom_feature: null
  bond_feature: null

task:
  class: InteractionPrediction
  model:
    class: ESM
    path: ~/scratch/esm-model-weights/
    model: ESM-1b
    readout: mean
  model2:
    class: GlycanConvolutionalNetwork
    glycoword_dim: 216
    input_dim: 128
    hidden_dims: [128, 128]
    kernel_size: 5
    padding: 2
    readout: max
  criterion: mse
  metric: [ "mae", "rmse", "spearmanr" ]
  num_mlp_layer: 2

metric: root mean squared error [interaction]

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  gpus: {{ gpus }}
  batch_size: 32

train:
  num_epoch: 10

fix_encoder: True
