output_dir: ~/scratch/torchglycan_output/

dataset:
  class: GlycanClassification
  path: ~/scratch/glycan-datasets/
  target_fields: ["genus"]
  unit_feature: default
  link_feature: default

task:
  class: PropertyPrediction
  model:
    class: GlycanLSTM
    glycoword_dim: 216
    input_dim: 21
    hidden_dim: 640
    num_layers: 3
  criterion: ce
  metric: ["acc", "mcc"]
  num_class: 922

metric: accuracy [genus]

optimizer:
  class: Adam
  lr: 5.0e-5

engine:
  gpus: {{ gpus }}
  batch_size: 32

train:
  num_epoch: 50
